spring.application.name=CookingBrain

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.gbkktrxbuulingdxhiki
spring.datasource.password=389RN29FEJN2K459DUJ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://gbkktrxbuulingdxhiki.supabase.co/auth/v1

spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=${PORT:8080}